# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856efbe8dd9aa302e0ec26b29f5fc3f600a60bdb08eb121284d4bc48977063663038c9dc81cbe624bd2268d151eb9f13d11052ec656fa3c81b58e540f92a041a

test:
  secret_key_base: e27bd76c47d6ddb5a2d1d72932304c330e3da018a557432910903f6db897d88803759028d0318a1db2b33ebb55931aa660a8860464d5ddbc7d7e795e68806f22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
